### ISSUE TITLE
coredump on ESP8266 when sending UDP on missing network

### ISSUE THREAD

**Issue by ceco** [cesanta/mongoose-os#267]
Hi.

We get a coredump when trying to send UDP packet while connected in STA mode and there is no Internet connection.

Reproduce with the following example:
main.c:
```
#include "common/platform.h"
#include "fw/src/mgos_app.h"
#include "fw/src/mgos_mongoose.h"
#include "fw/src/mgos_sys_config.h"
#include "fw/src/mgos_wifi.h"
#include "fw/src/mgos_timers.h"
#include "frozen/frozen.h"

static const char* str_connect_uri = "udp://pool.ntp.org:123";
static struct mg_connection* sntp_nc = NULL;
static char str_sntp_request[48];

// Main network connection handler
void sntp_connection_handler(struct mg_connection *nc, int ev, void *ev_data, void *user_data) {
    (void) user_data;
    (void) nc;
    (void) ev_data;
    if (ev != MG_EV_POLL) {
        LOG(LL_DEBUG, ("sntp nc event %d", ev));
    }
}

struct mg_connection* sntp_bind() {
    struct mg_connection* nc = mg_connect(mgos_get_mgr(), str_connect_uri, sntp_connection_handler, NULL);
    if (nc == NULL) {
        LOG(LL_ERROR, ("unable to create SNTP UDP socket"));
    }
    return nc;
}

static void send_timer(void* arg) {
    (void)arg;
    char* ip = mgos_wifi_get_sta_ip();

    if(mgos_wifi_get_status() == MGOS_WIFI_IP_ACQUIRED && ip != NULL) {
        LOG(LL_INFO,("Try send"));
        mg_send(sntp_nc, str_sntp_request, sizeof(str_sntp_request));
    }

    free(ip);
}

enum mgos_app_init_result mgos_app_init(void) {
    // Create the UDP socket connection which is never destroyed
    sntp_nc = sntp_bind();

    // Initialize sntp request buffer, which never mutates
    memset(str_sntp_request, 0, sizeof(str_sntp_request));
    str_sntp_request[0] = '\x1b';

    // Start send timer
    mgos_set_timer(200, true, send_timer, NULL);

    return MGOS_APP_INIT_SUCCESS;
}
```
mos.yml
```
name: c_network
# arch: PLATFORM
version: 1.0
skeleton_version: 2017-03-17
sources:
  - src
filesystem:
build_vars:
  MGOS_ENABLE_DNS_SD: 0
  MGOS_ENABLE_UPDATER_POST: 1
  MGOS_ENABLE_SNTP: 0
  MGOS_ENABLE_MQTT: 0
  MGOS_ENABLE_ATCA: 0
  MGOS_ENABLE_ATCA_SERVICE: 0 
  MGOS_ENABLE_BITBANG: 0
  MGOS_ENABLE_RPC: 0
  MGOS_ENABLE_RPC_CHANNEL_HTTP: 0
  MGOS_ENABLE_RPC_CHANNEL_LOOPBACK: 0
  MGOS_ENABLE_RPC_CHANNEL_MQTT: 0
  MGOS_ENABLE_RPC_CHANNEL_UART: 0
  MGOS_ENABLE_DEBUG_UDP: 0
  APP_CONF_SCHEMA: src/conf_schema.yaml
```
conf_schema.yaml
```
[
  ["wifi.sta.enable", true],
  ["wifi.ap.enable", false],
  ["wifi.sta.ssid", "SSID"],
  ["wifi.sta.pass", "KEY"],
]
```
It seems the problem is in mg_send
```
void mg_send(struct mg_connection *nc, const void *buf, int len) {
  nc->last_io_time = (time_t) mg_time();
  if (nc->flags & MG_F_UDP) {
    nc->iface->vtable->udp_send(nc, buf, len);
  } else {
    nc->iface->vtable->tcp_send(nc, buf, len);
  }
}
```

```
dhcp client start...
mgos_wifi_on_change_ Wifi: connected
ip:192.168.63.140,mask:255.255.255.0,gw:192.168.63.1
mgos_wifi_on_change_ WiFi: ready, IP 192.168.63.140, DNS 192.168.63.1
send_timer           Try send

Exception 20 @ 0x00008000, vaddr 0x00008000
 A0: 0x40270ab4  A1: 0x3ffffe80  A2: 0x3ffef6cc  A3: 0x3ffee489
 A4: 0x00000030  A5: 0x00008000  A6: 0x7ff00000  A7: 0x7ff2af8d
 A8: 0x000003fe  A9: 0x58000000 A10: 0x00000403 A11: 0xfbe76c8b
A12: 0x3ffef6cc A13: 0x00000030 A14: 0x3ffee489 A15: 0x00000000

(exc SP: 0x3ffffce0)

--- BEGIN CORE DUMP ---
```
