### ISSUE TITLE
failed to set aws.thing_name

### ISSUE THREAD

**Issue by toabhisheksingh** [cesanta/mongoose-os#393]
When we run the mos aws-iot-setup command as described in https://aws.amazon.com/blogs/apn/aws-iot-on-mongoose-os-part-1/, we get the following error

Error: failed to set aws.thing_name: no config value at path "aws.thing_name"

**Comment by tefan57** [comment]
I had this same issue while trying to build using c, turns out you need to add

- origin: https://github.com/mongoose-os-libs/aws

in libs.

Adding this line removed that exact error.
Hope it helps!

**Comment by charles-d-burton** [comment]
This didn't work for me.

**Comment by tjm1** [comment]
I am getting the same error.  I see "Adding this line removed that exact error."  what line was added and where was it added? I am confused.

**Comment by Burt-Silverman** [comment]
Tim,
Look at the mos.yml file in the top level of the example (c_mqtt directory). You will see origin lines under libs. Add the one that tefan57 metions above.

**Comment by tjm1** [comment]
Burt
This did not work for me. I get the same error Like Charles earlier.

**Comment by Burt-Silverman** [comment]
Do not forget to reflash after rebuilding. It is easy to make this mistake.

**Comment by mike-rogers** [comment]
I ran into this too. To be clear, the solution is to modify your `mos.yaml`. Look for the section that begins:

```yaml
libs:
  - origin: https://github.com/mongoose-os-libs/ca-bundle
  - origin: https://github.com/mongoose-os-libs/http-server
  - origin: https://github.com/mongoose-os-libs/ota-http-server
  - origin: https://github.com/mongoose-os-libs/rpc-loopback
  - origin: https://github.com/mongoose-os-libs/rpc-mqtt
  # other libs...
```

and add the following line:

```yaml
  - origin: https://github.com/mongoose-os-libs/aws
```

Then (per @Burt-Silverman) remember to `mos build` and `mos flash`.
